version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
  
7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Iluminati_Painbal_Bo\Debug\2D Physics - class 4.exe"
7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Iluminati_Painbal_Bo\Game\pinball"
7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Iluminati_Painbal_Bo\Game\*.dll"
7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\README.txt"

artifacts:
  - path: SpikeFromAppveyor.zip 
